"""Turn the report's data into numbers, tables, and figures.

    python scripts/make_figures.py

`build.py` runs this before every render, so changed data reaches the PDF
without touching the prose. Three outputs:

- `_variables.yml`: every number the prose quotes, computed from
  `data/model.json`. The text writes `{{< var trip.fuel_cost >}}`, never the
  number itself, so the PDF can't disagree with the model.
- `tables/*.md`: Markdown tables built from `data/*.csv`, pulled into the
  report with `{{< include tables/schedule.md >}}`.
- `figures/*.svg`: charts plotted from `data/*.csv`.

A project with its own model or map code calls it from here (or writes
these files some other way); the report only reads the results.
"""

import csv
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DATA, FIGS, TABLES = ROOT / "data", ROOT / "figures", ROOT / "tables"

plt.rcParams.update({
    "svg.fonttype": "none",       # keep text as text, not outlined paths
    "svg.hashsalt": "report",     # stable element ids -> clean git diffs
    "font.size": 8,
    "axes.grid": True,
    "grid.linewidth": 0.4,
    "grid.color": "#bbbbbb",
    "lines.linewidth": 1.4,
})


def read_csv(name):
    with open(DATA / name, newline="", encoding="utf-8") as f:
        return list(csv.reader(f))


def variables(model):
    """Numbers the prose quotes. Derived values are computed here, once."""
    t = model["trip"]
    hours = model["route_miles"] / t["slowest_pace_mph"]
    return {
        "trip": {
            "days": t["days"],
            "people": t["people"],
            "miles": t["miles"],
            "fuel_cost": f"${t['miles'] * t['cost_per_mile']:,.0f}",
            "lodging_cost": f"${t['lodging_per_night'] * (t['days'] - 1):,.0f}",
        },
        "route": {
            "miles": model["route_miles"],
            "hours_at_pace": f"{hours:.1f}",
            "daylight": t["daylight_hours"],
            "fits": "fits" if hours <= t["daylight_hours"] else "does not fit",
        },
    }


def yaml_lines(d, indent=0):
    """Tiny YAML writer (no PyYAML dependency): nested dicts of scalars."""
    out = []
    for k, v in d.items():
        if isinstance(v, dict):
            out.append(" " * indent + f"{k}:")
            out += yaml_lines(v, indent + 2)
        else:
            out.append(" " * indent + f"{k}: {json.dumps(v, ensure_ascii=False)}")
    return out


def md_table(rows, align=None):
    head, body = rows[0], [r for r in rows[1:] if r]
    align = align or ["---"] * len(head)
    lines = ["| " + " | ".join(head) + " |", "|" + "|".join(align) + "|"]
    lines += ["| " + " | ".join(r) + " |" for r in body]
    return "\n".join(lines) + "\n"


def elevation_plot(rows, svg):
    head, body = rows[0], [[float(v) for v in r] for r in rows[1:] if r]
    fig, ax = plt.subplots(figsize=(5.5, 2.2))
    ax.fill_between([r[0] for r in body], [r[1] for r in body], alpha=0.25)
    ax.plot([r[0] for r in body], [r[1] for r in body])
    ax.set_xlabel(head[0])
    ax.set_ylabel(head[1])
    fig.tight_layout()
    fig.savefig(svg, metadata={"Date": None})
    plt.close(fig)


def main():
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    FIGS.mkdir(exist_ok=True)
    TABLES.mkdir(exist_ok=True)

    model = json.loads((DATA / "model.json").read_text(encoding="utf-8"))
    (ROOT / "_variables.yml").write_text(
        "# Generated by scripts/make_figures.py from data/model.json. Don't edit;\n"
        "# change the data and rebuild.\n" + "\n".join(yaml_lines(variables(model))) + "\n",
        encoding="utf-8")
    print("  data/model.json -> _variables.yml")

    (TABLES / "schedule.md").write_text(
        md_table(read_csv("schedule.csv"), ["--:", "---", "--:", "---"]), encoding="utf-8")
    print("  data/schedule.csv -> tables/schedule.md")

    elevation_plot(read_csv("elevation.csv"), FIGS / "elevation.svg")
    print("  data/elevation.csv -> figures/elevation.svg")


if __name__ == "__main__":
    main()
